jobs:
  - build-test:
      context: lexio-package
      filters:
        branches:
          ignore:
            - main
  - send-slack-on-pr-success:
      requires:
        - build-test
      context: lexio-package
      filters:
        branches:
          ignore:
            - main
