description: Restores the build-test cache for pyenv, poetry, and pre-commit
steps:
  - restore_cache:
      keys:
        - v1-pyenv-{{ arch }}-sfn-workflow-client-{{ checksum "poetry.lock" }}
  - restore_cache:
      keys:
        - v1-poetry-{{ arch }}-sfn-workflow-client-{{ checksum "poetry.lock" }}
  - restore_cache:
      keys:
        - v1-precommit-{{ arch }}-sfn-workflow-client-{{ checksum ".pre-commit-config.yaml" }}
